#!/usr/bin/env bash
# configure my domain zone:
# www --> 480692-lb-01 18.210.16.249
# web-01 --> 480692-web-01 100.26.215.114
# web-02 --> 480692-web-02 100.25.45.160

subdomains_all=( "www" "lb-01" "web-01" "web-02" )

runDig () {
	local subdomain=$1
	local domain=$2

	dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
	domain="$1"
	for i in "${subdomains_all[@]}"
	do
		runDig "$i" "$domain"
	done
elif [ $# -eq 2 ]; then
	domain="$1"
	subdomain="$2"
	runDig "$subdomain" "$domain"
fi
