#!/usr/bin/bash
# installl nginx on web-01



sudo apt-get update
sudo apt-get install -y nginx
service nginx start
sudo bash -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        return 200 \"Hello World!\";
    }
}" > /etc/nginx/sites-available/default'
sudo service restart
