#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

VARIABLE=0
while [ $VARIABLE -lt 10 ]
do 
	if [ $VARIABLE = 4 ]
	then
		echo "bad luck"
	elif [ $VARIABLE = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	let VARIABLE+=1
done
